name: TEST
on:
  push:
    paths:
      - "**.scss"
      - "*.html"
      - "*.shtm"
  workflow_dispatch:
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install firefox
          curl --silent --location https://github.com/sass/dart-sass/releases/download/1.53.0/dart-sass-1.53.0-linux-x64.tar.gz | tar --extract --gzip
          mv dart-sass/sass /usr/local/bin
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Compile artifacts from changed files
        # NOTE the GROUPS secret must be single-quoted because it contains JSON
        run: python TEST-compile.py "$f" '${{ secrets.GROUPS }}' --github-commit ${{ github.repository }}/commit/${{ github.sha }}
      - name: ðŸž artifacts
        run: echo world > artifacts/hello.txt && ls artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ github.workflow }}-${{ github.run_number }}
          path: artifacts
      - name: Deploy artifacts
        # NOTE the GROUPS secret must be single-quoted because it contains JSON
        run: python TEST-deploy.py ${{ secrets.ADMIN_BASE_URL }} ${{ secrets.ADMIN_USERNAME }} ${{ secrets.ADMIN_PASSWORD }} '${{ secrets.GROUPS }}'
